
export const HOTEL_BY_PRICE_REQUEST = "HOTEL_BY_PRICE_REQUEST"
export const HOTEL_BY_PRICE_SUCCESS = "HOTEL_BY_PRICE_SUCCESS"
export const HOTEL_BY_PRICE_FAIL = "HOTEL_BY_PRICE_FAIL"



export const SERACH_HOTEL_REQUEST = "SERACH_HOTEL_REQUEST"
export const SERACH_HOTEL_SUCCESS = "SERACH_HOTEL_SUCCESS"
export const SERACH_HOTEL_FAIL = "SERACH_HOTEL_FAIL"



export const CATEGORY_HOTEL_REQUEST = "CATEGORY_HOTEL_REQUEST"
export const CATEGORY_HOTEL_SUCCESS = "CATEGORY_HOTEL_SUCCESS"
export const CATEGORY_HOTEL_FAIL = "SERACH_HOTEL_FAIL"